### ISSUE TITLE
Reduce duplicate code

### ISSUE THREAD

**Issue by afmenez** [SeungheonOh/EmojiTools#6]
There's no need to have 4 almost identical implementations of the `deEmojize()` functions. You can eliminate 2 of them by using default parameters:

`std::string deEmojize(std::string s, std::string dividerFront = ":", std::string dividerRear = ":");`

`void deEmojize(std::string *s, std::string dividerFront = ":", std::string dividerRear = ":");`

**Comment by SeungheonOh** [comment]
Newb mistake,,  Working on it

**Comment by SeungheonOh** [comment]
updated in https://github.com/SeungheonOh/EmojiTools/commit/73d799eda5fcfc1f670ae02bb03f89e1867f12bb
