### ISSUE TITLE
Use templates to be more flexible with the parameter types

### ISSUE THREAD

**Issue by afmenez** [SeungheonOh/EmojiTools#7]
You can use templates to accept more parameter types.  The dividers currently must be `std::string`, but it would be nice to accept also a `char` for example.

`template <class Str, class Sep> Str deEmojize(Str s, Sep dividerFront, Sep dividerRear);`
`template <class Str, class Sep> void deEmojize(Str *s, Sep dividerFront, Sep dividerRear);`

**Comment by SeungheonOh** [comment]
done in https://github.com/SeungheonOh/EmojiTools/commit/d1330660259f2c35f8877e5587a24eb0593ab281
